# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad48ee1f2222a379a09984442b083b6cfeb4e524e58f8735ffe5959fa16c84bdef9ab49e4f034b4382686f7d6396f23a36b2daeb25869694725c18420a2c9d4

test:
  secret_key_base: 6c93aa99199d2d718357f240e9321b07afffbc3b51f84f4a92b48398893d0631de618dc46e8f9eed8d6bd662b05dacee6605ae49fd4d87cce2a0fbf979291c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
